#include <ntddk.h>
#include "msdsm.tmh" // Generated by WPP
#include "msdsmwmi.h" // Generated from MOF

NTSTATUS DriverEntry(
    _In_ PDRIVER_OBJECT  DriverObject,
    _In_ PUNICODE_STRING RegistryPath
)
{
    // ...
    return STATUS_SUCCESS;
}
