#include <stdio.h>
#include <sys/types.h>
#include <Rectangle.h> /* This file will be generated by asn1c */

int main(int ac, char **av) {
    Rectangle_t *rect; /* Type defined in Rectangle.h */
    
    rect = calloc(1, sizeof(*rect));
    if(!rect) {
        perror("calloc() failed");
        return 1;
    }

    rect->height = 42;
    rect->width  = 23;

    printf("Rectangle: height=%ld, width=%ld\n", 
           (long)rect->height, (long)rect->width);
    
    return 0;
}
