add_rules("mode.debug", "mode.release")

target("metal_app")
    add_rules("xcode.application")
    add_includedirs("Renderer")
    add_frameworks("MetalKit")
    add_mflags("-fmodules")
    add_files("Renderer/*.m", "Renderer/*.metal")
    add_files("Application/main.m")
    add_files("Application/AAPLViewController.m")
    add_files("Application/macOS/Info.plist")
    add_files("Application/macOS/Base.lproj/*.storyboard")
    add_defines("TARGET_MACOS")
    add_frameworks("AppKit")
