add_rules("mode.debug", "mode.release")

toolchain("myclang")
    set_kind("standalone")
    set_toolset("cc", "clang")
    set_toolset("cxx", "clang++")
    set_toolset("ld", "clang++")
    on_check(function (toolchain)
        return import("lib.detect.find_tool")("clang")
    end)
    on_load(function (toolchain)
        toolchain:add("cxflags", "-DTEST_MACRO")
    end)
toolchain_end()

target("test")
    set_kind("binary")
    add_files("src/main.cpp")
    set_toolchains("myclang")
