#include <ntddk.h>
#include <wdf.h>
#include "nonpnp.tmh" // Generated by WPP

NTSTATUS DriverEntry(
    _In_ PDRIVER_OBJECT  DriverObject,
    _In_ PUNICODE_STRING RegistryPath
)
{
    // ...
    TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "%!FUNC! Entry");
    return STATUS_SUCCESS;
}
